### ISSUE TITLE
Add aid team script

### ISSUE THREAD

**Issue by dbalatero** [dbalatero/aid-flow#1]
# TODO

- [ ] `aid team list` shows the current team
- [ ] `aid team add` adds to the current team
- [ ] file format is standard
