### ISSUE TITLE
Add aid begin

### ISSUE THREAD

**Issue by dbalatero** [dbalatero/aid-flow#2]
# TODO

- [ ] Installs hub/ensures login
- [ ] Prompt for Github username
- [ ] Prompt for project manager IDs (asana project id, pivotal project id)
- [ ] Create a local branch
- [ ] Push branch to origin remote
- [ ] Start task on project tracker
- [ ] Open PR on Github
