### ISSUE TITLE
Add aid finish

### ISSUE THREAD

**Issue by dbalatero** [dbalatero/aid-flow#3]
# TODO

- [ ] Clean up feature branch
- [ ] Amend commit with finish message
- [ ] Force push with lease to origin
