### ISSUE TITLE
Add aid review

### ISSUE THREAD

**Issue by dbalatero** [dbalatero/aid-flow#4]
# TODO

- [ ] Prompt for reviewers
- [ ] Run `aid finish` if needed
- [ ] Change label from WIP -> reviewable
- [ ] Move task in project manager
- [ ] Mark PR ready for review
- [ ] Add reviewers to the PR
- [ ] Ping reviewers on Slack
